log:
  level: 5

replicaCount: 1
certDuration: 87600h
nameOverrider: ""
hostPath: /mnt/grit-agent

image:
  gritmanager:
    registry: ghcr.io
    repository: cumulus-compute-labs/grit-manager
    tag: dev
    pullSecrets: []
  gritagent:
    registry: ghcr.io
    repository: cumulus-compute-labs/grit-agent
    tag: dev
    pullSecrets: []

ports:
  metrics: 10351
  webhook: 10350
  healthProbe: 10352

resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 256Mi

